version: '3'
services:
  db:
    build: ./docker_db
    volumes:
      - ./docker_db/pgdata:/pgdata
      - ./docker_db/migrations:/docker-entrypoint-initdb.d/
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata

  backend:
    # environment:
    #   - GOPATH=/go/src/atmiguel/cerealnotes/
    environment:
      - DATABASE_URL=postgresql://docker:docker@db:5432?sslmode=disable
      - PORT=8080
      - TOKEN_SIGNING_KEY=AllYourBase
    build:
      context: ./
      args:
        app_env: ${APP_ENV} 
    volumes:
      - .:/go/src/github.com/atmiguel/cerealnotes/
    ports:
      - "8080:8080"
    links:
      - db